name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        configuration: [Debug, Release]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore src/KeyOverlayFPS.csproj
      
    - name: Build application
      run: dotnet build src/KeyOverlayFPS.csproj --configuration ${{ matrix.configuration }} --no-restore
      
    - name: Run tests
      run: dotnet test tests/KeyOverlayFPS.Tests.csproj --configuration ${{ matrix.configuration }} --no-build --verbosity normal
      
    - name: Upload build artifacts (Release only)
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-${{ github.sha }}
        path: |
          src/bin/Release/
          !src/bin/Release/**/*.pdb
        retention-days: 7